# Generated by Django 5.2 on 2026-08-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(blank=True, default='Error', max_length=255)),
                ('stack', models.TextField(blank=True, default='')),
                ('component_stack', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('error_type', models.CharField(blank=True, default='custom', max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Client Error Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='/', max_length=1000)),
                ('view_name', models.CharField(blank=True, default='App', max_length=255)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('fcp', models.FloatField(blank=True, help_text='First Contentful Paint (ms)', null=True)),
                ('lcp', models.FloatField(blank=True, help_text='Largest Contentful Paint (ms)', null=True)),
                ('cls', models.FloatField(blank=True, help_text='Cumulative Layout Shift (unitless)', null=True)),
                ('fid', models.FloatField(blank=True, help_text='First Input Delay (ms)', null=True)),
                ('inp', models.FloatField(blank=True, help_text='Interaction to Next Paint (ms)', null=True)),
                ('ttfb', models.FloatField(blank=True, help_text='Time to First Byte (ms)', null=True)),
                ('dom_complete', models.FloatField(blank=True, help_text='DOM Complete (ms)', null=True)),
                ('page_load_time', models.FloatField(blank=True, help_text='Total page load time (ms)', null=True)),
                ('route_transition_time', models.FloatField(blank=True, help_text='Client-side route transition (ms)', null=True)),
                ('device_memory', models.FloatField(blank=True, help_text='Device memory (GB)', null=True)),
                ('effective_connection_type', models.CharField(blank=True, default='4g', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
