# Generated by Django 6.1 on 2026-08-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier', models.CharField(default='Vendora Logistics', max_length=100)),
                ('carrier_service', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=30)),
                ('status_text', models.CharField(blank=True, default='', max_length=255)),
                ('current_location', models.CharField(blank=True, default='', max_length=255)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Shipment Trackings',
            },
        ),
        migrations.CreateModel(
            name='TrackingMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('current', models.BooleanField(default=False)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='orders.shipmenttracking')),
            ],
            options={
                'verbose_name_plural': 'Tracking Milestones',
                'ordering': ['timestamp'],
            },
        ),
    ]
