# Generated by Django 5.2.17 on 2026-08-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_brand_product_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, default=dict, help_text='Variant options (e.g., {"colors": ["Red", "Blue"], "sizes": ["S", "M", "L"]})'),
        ),
    ]
