# Generated by Django 5.2.17 on 2026-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users who found this review helpful'),
        ),
        migrations.AddField(
            model_name='review',
            name='verified_purchase',
            field=models.BooleanField(default=False, help_text='Whether the reviewer purchased the product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='User notes about this wishlist item'),
        ),
    ]
